### ISSUE TITLE
Add getting started guide to README

### ISSUE THREAD

**Issue by JoeProgrammer88** [JoeProgrammer88/DeepRacer#2]
These are some of the main points we will need to address in this repo. We may only need to supplement or link to the official AWS DeepRacer documentation for most of these things.

- [X] Setup Instructions: Issue #4
- [ ] Using pretrained model: Issue #6 
- [x] Setup WiFi: Issue #3
- [ ] Setup dev environment
- [ ] Customize the model
- [ ] Using the Simulator
